refactor(workflow): merge from main to dev/4.2.x (#74)
* [Feature]: support ODP Sharding MySQL and MySQL (#34)

* support ODP Sharding MySQL and MySQL

* modify mysql odc_version_diff_config

* Partition plan adaptation to database management. (#54)

* commit test.

* Partition plan adaptation to database management

* response comment

* response comment

* init flow instance id

* delete confirm node and fix api request parameter.

* update mapper to latest version.

* refine(workflow): add new workflow for building artifact and refine config (#61)

* refine: workflow

* response to CR

* rollback build_release

* refine

* fix(workflow): build rpm failed when execute build_artifact.yaml (#72)

* refine

* fix: build rpm execute failed

* refine

---------

Co-authored-by: zhangxiao <140503120+PeachThinking@users.noreply.github.com>
Co-authored-by: guowl3 <70270140+guowl3@users.noreply.github.com>
Co-authored-by: gaoda.xy <gaoda.xy@oceanbase.com>

diff --git a/.github/workflows/build_artifact.yaml b/.github/workflows/build_artifact.yaml
--- a/.github/workflows/build_artifact.yaml
+++ b/.github/workflows/build_artifact.yaml
@@ -1,24 +1,39 @@
 ###
-# This workflow is used for release
+# This workflow is used for quickly building artifacts
 # Triggers:
 #   1. Manual trigger
 # Jobs:
-#   1. Check Code Format
-#   2. PMD Scan
-#   3. Unit Test (TODO)
-#   4. Calculate Version Number
-#   5. Build Web Artifact (include front resource and only x86_64 platform for now)
-#   6. Build Client Artifact
-#   7. Release (TODO)
-#   8. Tag (TODO)
+#   1. Calculate Version Number
+#   2. Build Web Artifact (include front resource and only x86_64 platform for now)
+#   3. Build Client Artifact
 ###
 
-name: Build Release
-run-name: Build Release triggered by ${{ github.actor }} 🎉
+name: Build Artifact
+run-name: Build Artifact triggered by ${{ github.actor }} 🛠️
 
 on:
   workflow_dispatch:
     inputs:
+      build_jar:
+        description: "Build jar package"
+        required: true
+        type: boolean
+        default: false
+      build_rpm:
+        description: "Build rpm package"
+        required: true
+        type: boolean
+        default: false
+      build_docker:
+        description: "Build docker image"
+        required: true
+        type: boolean
+        default: false
+      build_client:
+        description: "Build client"
+        required: true
+        type: boolean
+        default: false
       rpm_release:
         description: "Rpm release number"
         required: false
@@ -32,62 +47,10 @@ on:
 
 env:
   ODC_CURRENT_BRANCH: ${{ github.ref_name }}
-  ODC_TARGET_BRANCH: ${{ github.base_ref }}
 
 jobs:
-  check-format:
-    name: Check Code Format
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout workspace
-        uses: actions/checkout@v3
-      - name: Setup JDK 8
-        uses: actions/setup-java@v3
-        with:
-          java-version: "8"
-          distribution: "temurin"
-          cache: maven
-      - name: Check code format
-        run: mvn impsort:check formatter:validate
-      - name: Check license
-        run: mvn license:check
-
-  pmd-scan:
-    name: PMD Scan
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout workspace
-        uses: actions/checkout@v3
-      - name: Setup JDK 8
-        uses: actions/setup-java@v3
-        with:
-          java-version: "8"
-          distribution: "temurin"
-          cache: maven
-      - name: Build project
-        run: mvn clean install -Dmaven.test.skip=true
-      - name: Run PMD scan
-        run: mvn pmd:check
-
-  unit-test:
-    name: Unit Test (Skip for now)
-    needs: [ check-format, pmd-scan ]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout workspace
-        uses: actions/checkout@v3
-      - name: Setup JDK 8
-        uses: actions/setup-java@v3
-        with:
-          java-version: "8"
-          distribution: "temurin"
-          cache: maven
-      - name: Run unit test
-        run: echo "Skip for now 🤪"
-
   calculate-version:
     name: Calculate Version Number
-    needs: [ unit-test ]
     runs-on: ubuntu-latest
     outputs:
       odc_rpm_release_number: ${{ steps.calculate_version.outputs.odc_rpm_release_number }}
@@ -103,8 +66,8 @@ jobs:
           echo "odc_rpm_release_number=${odc_rpm_release_number}" >> $GITHUB_OUTPUT
           echo "odc_rpm_release_number=${odc_rpm_release_number}"
           branch_match_regex="^(((dev/)?[0-9]\\.[0-9]\\.([0-9]{1,2}|x))|(release\\S*))$"
-          tag_prefix=`[[ "${{ env.ODC_CURRENT_BRANCH }}" =~ ${branch_match_regex} ]] && echo "" || echo "test-"`
-          odc_docker_image_tag="${tag_prefix}$(cat distribution/odc-server-VER.txt)-${odc_rpm_release_number}"
+          tag_prefix=`[[ "${{ env.ODC_CURRENT_BRANCH }}" =~ ${branch_match_regex} ]] && echo "test" || echo "dev"`
+          odc_docker_image_tag="${tag_prefix}-$(cat distribution/odc-server-VER.txt)-${odc_rpm_release_number}"
           if [[ -n "${{ inputs.image_tag }}" ]]; then odc_docker_image_tag="${{ inputs.image_tag }}"; fi
           echo "odc_docker_image_tag=${odc_docker_image_tag}" >> $GITHUB_OUTPUT
           echo "odc_docker_image_tag=${odc_docker_image_tag}"
@@ -132,6 +95,7 @@ jobs:
         with:
           node-version: "16"
       - name: Build front static resources
+        if: ${{ github.event.inputs.build_jar == 'true' || github.event.inputs.build_rpm == 'true' || github.event.inputs.build_docker == 'true'}}
         run: |
           echo "Current directory: "`pwd`
           echo "Start build front static resources"
@@ -162,8 +126,9 @@ jobs:
           echo "RPM's version is "${new_version}
           mvn versions:set -DnewVersion="${new_version}"
           mvn versions:commit
-      - name: Build jar & rpm (x86_64)
+      - name: Build jar
         run: |
+          echo "Start build jar packages"
           echo "Start prepare oceanbase-client"
           pushd import
           echo "Current dir is "`pwd`
@@ -175,15 +140,12 @@ jobs:
           echo "Start build rpm package"
           mvn help:system
           mvn clean install -Dmaven.test.skip=true
-          mvn --file server/odc-server/pom.xml rpm:rpm -Drpm.prefix=/opt
-          echo "Build rpm package success"
-          rm --force --recursive --verbose distribution/docker/resources/odc-*.rpm
-          mkdir -p distribution/docker/resources/
-          mv --verbose server/odc-server/target/rpm/odc-server/RPMS/*/odc-*.rpm distribution/docker/resources/
-          mv --verbose server/odc-server/target/*-executable.jar distribution/jar/odc.jar
+          echo "Build jar packages success"
+          cp --verbose server/odc-server/target/*-executable.jar distribution/jar/odc.jar
           cp -fv distribution/jar/odc.jar distribution/jar/odc-slim.jar
           zip -d distribution/jar/odc-slim.jar "BOOT-INF/classes/static/*"
       - name: Upload jar
+        if: ${{ github.event.inputs.build_jar == 'true' || github.event.inputs.build_client == 'true'}}
         uses: actions/upload-artifact@v3
         with:
           name: odc-artifact-jar
@@ -191,12 +153,23 @@ jobs:
             distribution/plugins/*.jar
             distribution/starters/*.jar
             distribution/jar/*.jar
+      - name: Build rpm (x86_64)
+        if: ${{ github.event.inputs.build_rpm == 'true' || github.event.inputs.build_docker == 'true' }}
+        run: |
+          echo "Start build rpm package"
+          mvn --file server/odc-server/pom.xml rpm:rpm -Drpm.prefix=/opt
+          echo "Build rpm package success"
+          rm --force --recursive --verbose distribution/docker/resources/odc-*.rpm
+          mkdir -p distribution/docker/resources/
+          mv --verbose server/odc-server/target/rpm/odc-server/RPMS/*/odc-*.rpm distribution/docker/resources/
       - name: Upload rpm (x86_64)
+        if: ${{ github.event.inputs.build_rpm == 'true' }}
         uses: actions/upload-artifact@v3
         with:
           name: odc-server-${{ steps.set_release_version.outputs.new_version }}.x86_64.rpm
           path: distribution/docker/resources/odc-*.rpm
       - name: Build docker image (x86_64)
+        if: ${{ github.event.inputs.build_docker == 'true' }}
         run: |
           sed -e "s/DATE_CHANGE/$(date)/" -i distribution/docker/odc/Dockerfile
           echo "odc_docker_image_tag=${odc_docker_image_tag}"
@@ -205,6 +178,7 @@ jobs:
           docker save -o resources/odc-server-${odc_docker_image_tag}.tar.gz docker.io/oceanbase/odc-server:${odc_docker_image_tag}
           popd
       - name: Upload docker image (x86_64)
+        if: ${{ github.event.inputs.build_docker == 'true' }}
         uses: actions/upload-artifact@v3
         with:
           name: odc-server-${{ env.odc_docker_image_tag }}.tar.gz
@@ -213,6 +187,7 @@ jobs:
   build-client:
     name: Build Client Artifact
     needs: [ build-web-x86_64 ]
+    if: ${{ github.event.inputs.build_client == 'true' }}
     runs-on: macos-latest
     strategy:
       fail-fast: false
@@ -223,6 +198,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           submodules: "recursive"
+      # Build jar failed when run on macos-latest, so we need to build and upload jar on ubuntu-latest in the above job
       - name: Download resources
         uses: actions/download-artifact@v3
         with:
@@ -298,19 +274,3 @@ jobs:
             client/release/*.deb
             client/release/*.exe
             client/release/*.AppImage
-
-  release:
-    name: Release (Skip for now)
-    needs: [ build-client ]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Release artifacts
-        run: echo "Skip for now 🤪"
-
-  tag:
-    name: Tag (Skip for now)
-    needs: [ release ]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Tag release
-        run: echo "Skip for now 🤪"
