fix regex

diff --git a/.github/workflows/build_dev.yaml b/.github/workflows/build_dev.yaml
--- a/.github/workflows/build_dev.yaml
+++ b/.github/workflows/build_dev.yaml
@@ -31,9 +31,14 @@ jobs:
     steps:
       - name: Check pull request title
         run: |
-          PR_TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
-          echo "PR title is ${PR_TITLE}"
-          if [[ "${PR_TITLE}" =~ ^((.+\(.+\))|(.+)): .+$ ]]; then echo "PR title is valid"; else echo "PR title is invalid, please follow the specification"; exit 1; fi
+          pr_title=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
+          echo "PR title is ${pr_title}"
+          if [[ "${pr_title}" =~ ^((.+\(.+\))|(.+)):.+$ ]]; then 
+            echo "PR title is valid"; 
+          else
+            echo "PR title is invalid, please follow the specification described in https://www.conventionalcommits.org/en/v1.0.0/#summary"; 
+            exit 1; 
+          fi
   check-format:
     name: Check Code Format
     runs-on: ubuntu-latest
